
# /infra/monitoring/prometheus.yml

global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'live_controller'
    metrics_path: /metrics
    static_configs:
      - targets: ['live_controller:9100']

  - job_name: 'signal_engine'
    metrics_path: /metrics
    static_configs:
      - targets: ['signal_engine:9101']

  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb:9187']  # PostgreSQL exporter port
