# /infra/monitoring/prometheus.yml

# Prometheus configuration for monitoring the BTC/ETH/USDT trading system

global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'xalgo_trading_system'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'timescaledb'
    static_configs:
      - targets: ['localhost:9187'] # PostgreSQL exporter for TimescaleDB
