// src/core/signal/TradeSignal.hpp

#pragma once

/**
 * @file TradeSignal.hpp
 * @brief Defines the structure for trade signals generated by the SignalGenerator.
 */

#include <string>

namespace XAlgo {

/**
 * @struct TradeSignal
 * @brief Represents a trading signal with direction, price, symbol, and confidence strength.
 */
struct TradeSignal {
    std::string symbol; ///< Trading symbol associated with the signal (e.g., "EUR/USD" or "TRIANGULAR").
    double price;       ///< Price at which the signal was generated (spread or market price).
    int direction;      ///< Direction of the trade: +1 for Buy, -1 for Sell.
    double strength = 1.0; ///< Confidence score or signal strength (default = 1.0).

    /**
     * @brief Convenience check for buy signals.
     * @return True if signal direction is Buy.
     */
    bool isBuy() const {
        return direction > 0;
    }

    /**
     * @brief Convenience check for sell signals.
     * @return True if signal direction is Sell.
     */
    bool isSell() const {
        return direction < 0;
    }
};

} // namespace XAlgo
